import { neon } from '@neondatabase/serverless';
import { randomUUID } from 'node:crypto';
import { emptyState, emailSchema, stateSchema } from '../shared/schema.js';
import { hashPassword } from '../server/auth.js';
const sql = neon(process.env.DATABASE_URL_UNPOOLED || process.env.DATABASE_URL);
await sql`CREATE TABLE IF NOT EXISTS northstar_household (id integer PRIMARY KEY CHECK (id = 1), data jsonb NOT NULL, version integer NOT NULL DEFAULT 0)`;
await sql`INSERT INTO northstar_household (id,data) VALUES (1,${JSON.stringify(emptyState())}::jsonb) ON CONFLICT (id) DO NOTHING`;
// Identifies the transaction that last bumped `version`, so a save that lost the household's
// compare-and-swap cannot still apply its row writes (see compareAndSave in server/db.js).
await sql`ALTER TABLE northstar_household ADD COLUMN IF NOT EXISTS writer_token text`;
await sql`CREATE TABLE IF NOT EXISTS northstar_login_limits (key text PRIMARY KEY, attempts integer NOT NULL, reset_at timestamptz NOT NULL)`;

await sql`CREATE TABLE IF NOT EXISTS northstar_users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_household_members (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  user_id uuid NOT NULL REFERENCES northstar_users(id),
  role text NOT NULL CHECK (role IN ('owner','member')),
  added_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, user_id)
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_invitations (
  id uuid PRIMARY KEY,
  household_id integer NOT NULL REFERENCES northstar_household(id),
  email text NOT NULL,
  role text NOT NULL CHECK (role IN ('owner','member')),
  invited_by uuid REFERENCES northstar_users(id),
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  accepted_by uuid REFERENCES northstar_users(id)
)`;
// Single-use, expiring password reset tokens, generated by an owner for a member (mirrors
// northstar_invitations above). Only the hash is stored; the raw token is shown once.
await sql`CREATE TABLE IF NOT EXISTS northstar_password_resets (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES northstar_users(id),
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  used_at timestamptz
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_password_resets_user_idx ON northstar_password_resets (user_id)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_audit_log (
  id bigserial PRIMARY KEY,
  household_id integer NOT NULL REFERENCES northstar_household(id),
  user_id uuid REFERENCES northstar_users(id),
  action text NOT NULL,
  collection text,
  item_id text,
  item_name text,
  created_at timestamptz NOT NULL DEFAULT now()
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_audit_log_household_idx ON northstar_audit_log (household_id, created_at DESC)`;

// --- Relational household tables (inventory, shopping list, appliances, family plan, settings). ---
// These replace the single JSONB blob in northstar_household.data as the source of truth so that
// one edit only touches its own row instead of rewriting the entire household's state.
await sql`CREATE TABLE IF NOT EXISTS northstar_inventory (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'units',
  category text NOT NULL DEFAULT 'Gear',
  calories_per_unit numeric NOT NULL DEFAULT 0,
  hours_per_unit numeric NOT NULL DEFAULT 0,
  capacity_per_unit numeric NOT NULL DEFAULT 0,
  price numeric NOT NULL DEFAULT 0,
  gallons_per_unit numeric NOT NULL DEFAULT 0,
  target numeric NOT NULL DEFAULT 0,
  store text NOT NULL DEFAULT '',
  emoji text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  macro_tag text NOT NULL DEFAULT '',
  fuel_type text NOT NULL DEFAULT '',
  purchase_date text NOT NULL DEFAULT '',
  expiry_date text NOT NULL DEFAULT '',
  barcode text NOT NULL DEFAULT '',
  recurring_days integer NOT NULL DEFAULT 0,
  PRIMARY KEY (household_id, id)
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_shopping_items (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'units',
  category text NOT NULL DEFAULT 'Gear',
  calories_per_unit numeric NOT NULL DEFAULT 0,
  hours_per_unit numeric NOT NULL DEFAULT 0,
  capacity_per_unit numeric NOT NULL DEFAULT 0,
  price numeric NOT NULL DEFAULT 0,
  gallons_per_unit numeric NOT NULL DEFAULT 0,
  target numeric NOT NULL DEFAULT 0,
  store text NOT NULL DEFAULT '',
  emoji text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  macro_tag text NOT NULL DEFAULT '',
  fuel_type text NOT NULL DEFAULT '',
  purchase_date text NOT NULL DEFAULT '',
  expiry_date text NOT NULL DEFAULT '',
  barcode text NOT NULL DEFAULT '',
  recurring_days integer NOT NULL DEFAULT 0,
  PRIMARY KEY (household_id, id)
)`;
// Existing deployments created these tables before barcode/recurring_days existed.
await sql`ALTER TABLE northstar_inventory ADD COLUMN IF NOT EXISTS barcode text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE northstar_inventory ADD COLUMN IF NOT EXISTS recurring_days integer NOT NULL DEFAULT 0`;
await sql`ALTER TABLE northstar_shopping_items ADD COLUMN IF NOT EXISTS barcode text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE northstar_shopping_items ADD COLUMN IF NOT EXISTS recurring_days integer NOT NULL DEFAULT 0`;
// Where the item is physically stored, and which kit (if any) it counts toward. Additive columns
// so existing rows default to "unassigned" (see itemSchema.location/kitId in shared/schema.js).
await sql`ALTER TABLE northstar_inventory ADD COLUMN IF NOT EXISTS location text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE northstar_inventory ADD COLUMN IF NOT EXISTS kit_id text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE northstar_shopping_items ADD COLUMN IF NOT EXISTS location text NOT NULL DEFAULT ''`;
await sql`ALTER TABLE northstar_shopping_items ADD COLUMN IF NOT EXISTS kit_id text NOT NULL DEFAULT ''`;
await sql`CREATE TABLE IF NOT EXISTS northstar_appliances (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  name text NOT NULL,
  watts numeric NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  priority text NOT NULL DEFAULT 'normal',
  PRIMARY KEY (household_id, id)
)`;
// Existing deployments created this table before outage load-shedding priorities existed.
await sql`ALTER TABLE northstar_appliances ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'normal'`;
await sql`CREATE TABLE IF NOT EXISTS northstar_reminders (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  title text NOT NULL,
  category text NOT NULL DEFAULT 'Other',
  recurring_days integer NOT NULL DEFAULT 90,
  notes text NOT NULL DEFAULT '',
  start_date text NOT NULL DEFAULT '',
  last_completed_date text NOT NULL DEFAULT '',
  snoozed_until text NOT NULL DEFAULT '',
  PRIMARY KEY (household_id, id)
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_checklist_checks (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  completed_at text NOT NULL DEFAULT '',
  PRIMARY KEY (household_id, id)
)`;
// --- Storage kits (go-bag, basement, vehicle, ...). target_contents is a small denormalized
// JSON list (name/quantity/unit) rather than its own table: it belongs to the kit alone, nothing
// else references a row within it, and it never grows large enough to need its own indexing.
await sql`CREATE TABLE IF NOT EXISTS northstar_kits (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  name text NOT NULL,
  purpose text NOT NULL DEFAULT '',
  target_contents jsonb NOT NULL DEFAULT '[]',
  PRIMARY KEY (household_id, id)
)`;
// --- Medications and prescriptions: sensitive household health data (see README privacy notes). ---
await sql`CREATE TABLE IF NOT EXISTS northstar_medications (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  id text NOT NULL,
  seq bigserial,
  person text NOT NULL DEFAULT '',
  name text NOT NULL,
  dose text NOT NULL DEFAULT '',
  quantity_on_hand numeric NOT NULL DEFAULT 0,
  refill_date text NOT NULL DEFAULT '',
  prescriber text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  PRIMARY KEY (household_id, id)
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_reminder_history (
  id bigserial PRIMARY KEY,
  household_id integer NOT NULL REFERENCES northstar_household(id),
  reminder_id text,
  reminder_title text,
  category text,
  event text NOT NULL CHECK (event IN ('completed','snoozed')),
  event_date text,
  user_id uuid REFERENCES northstar_users(id),
  created_at timestamptz NOT NULL DEFAULT now()
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_reminder_history_household_idx ON northstar_reminder_history (household_id, created_at DESC)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_plan (
  household_id integer PRIMARY KEY REFERENCES northstar_household(id),
  shelter_spot text NOT NULL DEFAULT '',
  meeting_primary text NOT NULL DEFAULT '',
  meeting_secondary text NOT NULL DEFAULT ''
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_family_members (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  position integer NOT NULL,
  name text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT '',
  dob text NOT NULL DEFAULT '',
  kind text NOT NULL DEFAULT 'person',
  calories_per_day numeric,
  water_gallons_per_day numeric,
  PRIMARY KEY (household_id, position)
)`;
// Existing deployments created this table before per-member consumption figures existed. A NULL
// override means "use the configured per-person default"; pets default to counting for nothing
// until their own figures are entered (see householdNeeds in shared/readiness.js).
await sql`ALTER TABLE northstar_family_members ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'person'`;
await sql`ALTER TABLE northstar_family_members ADD COLUMN IF NOT EXISTS calories_per_day numeric`;
await sql`ALTER TABLE northstar_family_members ADD COLUMN IF NOT EXISTS water_gallons_per_day numeric`;
await sql`CREATE TABLE IF NOT EXISTS northstar_contacts (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  position integer NOT NULL,
  name text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT '',
  PRIMARY KEY (household_id, position)
)`;
await sql`CREATE TABLE IF NOT EXISTS northstar_settings (
  household_id integer PRIMARY KEY REFERENCES northstar_household(id),
  household_size integer NOT NULL DEFAULT 4,
  calories_per_person_per_day numeric NOT NULL DEFAULT 2000,
  water_gallons_per_person_per_day numeric NOT NULL DEFAULT 1,
  survival_goal_days integer NOT NULL DEFAULT 14,
  heat_goal_hours numeric NOT NULL DEFAULT 36,
  power_goal_kwh numeric NOT NULL DEFAULT 20,
  battery_usable_fraction numeric NOT NULL DEFAULT 0.9,
  inverter_efficiency numeric NOT NULL DEFAULT 0.9
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_inventory_household_category_idx ON northstar_inventory (household_id, category)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_shopping_items_household_category_idx ON northstar_shopping_items (household_id, category)`;

// --- Encrypted, scheduled household backups (see api/backup.js and server/backupCrypto.js). ---
await sql`CREATE TABLE IF NOT EXISTS northstar_backups (
  id bigserial PRIMARY KEY,
  household_id integer NOT NULL REFERENCES northstar_household(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL CHECK (status IN ('success','failed')),
  error text,
  checksum text,
  size_bytes integer,
  inventory_count integer,
  shopping_count integer,
  appliance_count integer,
  has_plan boolean,
  iv bytea,
  auth_tag bytea,
  ciphertext bytea
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_backups_household_idx ON northstar_backups (household_id, created_at DESC)`;

// --- Production monitoring: per-minute request metrics and alert de-duplication state. ---
// Deliberately content-free (route, outcome, status, latency only) so operational history can
// be retained and read without exposing household data. Pruned by the daily maintenance cron.
await sql`CREATE TABLE IF NOT EXISTS northstar_request_metrics (
  bucket timestamptz NOT NULL,
  route text NOT NULL,
  outcome text NOT NULL,
  status integer NOT NULL,
  requests integer NOT NULL DEFAULT 0,
  latency_ms_total bigint NOT NULL DEFAULT 0,
  latency_ms_max integer NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket, route, outcome, status)
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_request_metrics_recent_idx ON northstar_request_metrics (bucket DESC)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_request_metrics_route_idx ON northstar_request_metrics (route, outcome, bucket DESC)`;
// --- Readiness history: one aggregate snapshot per household per day. ---
// Deliberately content-free in the same way request metrics are: days of supply, totals and
// counts only, never item names, quantities or categories. That keeps the history safe to
// retain (and to read) independently of the household data it describes. The primary key is
// (household_id, day), so re-running the daily cron updates that day rather than duplicating it.
await sql`CREATE TABLE IF NOT EXISTS northstar_readiness_history (
  household_id integer NOT NULL REFERENCES northstar_household(id),
  day date NOT NULL,
  water_days numeric NOT NULL DEFAULT 0,
  food_days numeric NOT NULL DEFAULT 0,
  power_days numeric NOT NULL DEFAULT 0,
  fuel_hours numeric NOT NULL DEFAULT 0,
  item_count integer NOT NULL DEFAULT 0,
  low_stock integer NOT NULL DEFAULT 0,
  expired integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (household_id, day)
)`;
await sql`CREATE INDEX IF NOT EXISTS northstar_readiness_history_day_idx ON northstar_readiness_history (household_id, day DESC)`;

await sql`CREATE TABLE IF NOT EXISTS northstar_alert_state (
  key text PRIMARY KEY,
  last_sent_at timestamptz NOT NULL DEFAULT now()
)`;

// One-time backfill: copy the existing JSONB row into the new relational tables. Only runs while
// the relational tables are still empty, so it's safe to leave in place and re-run this script.
const [{count: inventoryRows}] = await sql`SELECT count(*)::int AS count FROM northstar_inventory`;
const [{count: settingsRows}] = await sql`SELECT count(*)::int AS count FROM northstar_settings`;
if (inventoryRows === 0 && settingsRows === 0) {
  const [existing] = await sql`SELECT data FROM northstar_household WHERE id = 1`;
  if (existing) {
    // The pre-relational JSONB blob predates reminders/checklists; default them so old rows still parse.
    const state = stateSchema.parse({reminders: [], checklistChecks: [], ...existing.data});
    for (const item of state.inventory) {
      await sql`INSERT INTO northstar_inventory (household_id, id, name, quantity, unit, category, calories_per_unit, hours_per_unit, capacity_per_unit, price, gallons_per_unit, target, store, emoji, image, macro_tag, fuel_type, purchase_date, expiry_date)
        VALUES (1, ${item.id}, ${item.name}, ${item.quantity}, ${item.unit}, ${item.category}, ${item.caloriesPerUnit}, ${item.hoursPerUnit}, ${item.capacityPerUnit}, ${item.price}, ${item.gallonsPerUnit}, ${item.target}, ${item.store}, ${item.emoji}, ${item.image}, ${item.macroTag}, ${item.fuelType}, ${item.purchaseDate}, ${item.expiryDate})
        ON CONFLICT (household_id, id) DO NOTHING`;
    }
    for (const item of state.shoppingList) {
      await sql`INSERT INTO northstar_shopping_items (household_id, id, name, quantity, unit, category, calories_per_unit, hours_per_unit, capacity_per_unit, price, gallons_per_unit, target, store, emoji, image, macro_tag, fuel_type, purchase_date, expiry_date)
        VALUES (1, ${item.id}, ${item.name}, ${item.quantity}, ${item.unit}, ${item.category}, ${item.caloriesPerUnit}, ${item.hoursPerUnit}, ${item.capacityPerUnit}, ${item.price}, ${item.gallonsPerUnit}, ${item.target}, ${item.store}, ${item.emoji}, ${item.image}, ${item.macroTag}, ${item.fuelType}, ${item.purchaseDate}, ${item.expiryDate})
        ON CONFLICT (household_id, id) DO NOTHING`;
    }
    for (const appliance of state.appliances) {
      await sql`INSERT INTO northstar_appliances (household_id, id, name, watts, hours, active, priority)
        VALUES (1, ${appliance.id}, ${appliance.name}, ${appliance.watts}, ${appliance.hours}, ${appliance.active}, ${appliance.priority || 'normal'})
        ON CONFLICT (household_id, id) DO NOTHING`;
    }
    if (state.plan) {
      await sql`INSERT INTO northstar_plan (household_id, shelter_spot, meeting_primary, meeting_secondary)
        VALUES (1, ${state.plan.shelterSpot}, ${state.plan.meetingPoints.primary}, ${state.plan.meetingPoints.secondary})
        ON CONFLICT (household_id) DO NOTHING`;
      for (let position = 0; position < state.plan.family.length; position++) {
        const member = state.plan.family[position];
        await sql`INSERT INTO northstar_family_members (household_id, position, name, role, dob)
          VALUES (1, ${position}, ${member.name}, ${member.role}, ${member.dob})
          ON CONFLICT (household_id, position) DO NOTHING`;
      }
      for (let position = 0; position < state.plan.contacts.length; position++) {
        const contact = state.plan.contacts[position];
        await sql`INSERT INTO northstar_contacts (household_id, position, name, phone, type)
          VALUES (1, ${position}, ${contact.name}, ${contact.phone}, ${contact.type})
          ON CONFLICT (household_id, position) DO NOTHING`;
      }
    }
    await sql`INSERT INTO northstar_settings (household_id, household_size, calories_per_person_per_day, water_gallons_per_person_per_day, survival_goal_days, heat_goal_hours, power_goal_kwh, battery_usable_fraction, inverter_efficiency)
      VALUES (1, ${state.settings.householdSize}, ${state.settings.caloriesPerPersonPerDay}, ${state.settings.waterGallonsPerPersonPerDay}, ${state.settings.survivalGoalDays}, ${state.settings.heatGoalHours}, ${state.settings.powerGoalKwh}, ${state.settings.batteryUsableFraction}, ${state.settings.inverterEfficiency})
      ON CONFLICT (household_id) DO NOTHING`;
    console.log(`Backfilled relational tables from the existing household row (${state.inventory.length} inventory, ${state.shoppingList.length} shopping list, ${state.appliances.length} appliances).`);
  }
} else {
  console.log('Relational household tables already contain data; skipping JSONB backfill.');
}

// One-time bootstrap: migrating from the shared-password login creates the first owner
// account from HOUSEHOLD_OWNER_EMAIL/HOUSEHOLD_PASSWORD. It only ever runs while no
// accounts exist yet, so it's safe to leave both variables set after the first run.
const [{count}] = await sql`SELECT count(*)::int AS count FROM northstar_users`;
if (count === 0 && process.env.HOUSEHOLD_OWNER_EMAIL && process.env.HOUSEHOLD_PASSWORD) {
  const email = emailSchema.parse(process.env.HOUSEHOLD_OWNER_EMAIL);
  const userId = randomUUID();
  await sql.transaction(tx => [
    tx`INSERT INTO northstar_users (id, email, password_hash) VALUES (${userId}, ${email}, ${hashPassword(process.env.HOUSEHOLD_PASSWORD)})`,
    tx`INSERT INTO northstar_household_members (household_id, user_id, role) VALUES (1, ${userId}, 'owner')`,
  ]);
  console.log(`Created the first owner account for ${email}. The shared HOUSEHOLD_PASSWORD login no longer works; sign in with this email and password instead.`);
} else if (count === 0) {
  console.log('No accounts exist yet. Set HOUSEHOLD_OWNER_EMAIL and HOUSEHOLD_PASSWORD, then re-run this migration to create the first owner account.');
}

console.log('Database schema ready. Existing household data preserved.');
